/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class AAdcExp1 extends PExp1
{
    private PExp1 _left_;
    private TAdc _adc_;
    private PExp2 _right_;

    public AAdcExp1()
    {
        // Constructor
    }

    public AAdcExp1(
        @SuppressWarnings("hiding") PExp1 _left_,
        @SuppressWarnings("hiding") TAdc _adc_,
        @SuppressWarnings("hiding") PExp2 _right_)
    {
        // Constructor
        setLeft(_left_);

        setAdc(_adc_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new AAdcExp1(
            cloneNode(this._left_),
            cloneNode(this._adc_),
            cloneNode(this._right_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAdcExp1(this);
    }

    public PExp1 getLeft()
    {
        return this._left_;
    }

    public void setLeft(PExp1 node)
    {
        if(this._left_ != null)
        {
            this._left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._left_ = node;
    }

    public TAdc getAdc()
    {
        return this._adc_;
    }

    public void setAdc(TAdc node)
    {
        if(this._adc_ != null)
        {
            this._adc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._adc_ = node;
    }

    public PExp2 getRight()
    {
        return this._right_;
    }

    public void setRight(PExp2 node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._left_)
            + toString(this._adc_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._left_ == child)
        {
            this._left_ = null;
            return;
        }

        if(this._adc_ == child)
        {
            this._adc_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._left_ == oldChild)
        {
            setLeft((PExp1) newChild);
            return;
        }

        if(this._adc_ == oldChild)
        {
            setAdc((TAdc) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((PExp2) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
