/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class AAdcOpExp extends POpExp
{
    private PExp _exp_;
    private TAdc _adc_;

    public AAdcOpExp()
    {
        // Constructor
    }

    public AAdcOpExp(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TAdc _adc_)
    {
        // Constructor
        setExp(_exp_);

        setAdc(_adc_);

    }

    @Override
    public Object clone()
    {
        return new AAdcOpExp(
            cloneNode(this._exp_),
            cloneNode(this._adc_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAdcOpExp(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TAdc getAdc()
    {
        return this._adc_;
    }

    public void setAdc(TAdc node)
    {
        if(this._adc_ != null)
        {
            this._adc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._adc_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._adc_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._adc_ == child)
        {
            this._adc_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._adc_ == oldChild)
        {
            setAdc((TAdc) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
