/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class AAndExp4 extends PExp4
{
    private PExp4 _left_;
    private TELogico _eLogico_;
    private PExp5 _right_;

    public AAndExp4()
    {
        // Constructor
    }

    public AAndExp4(
        @SuppressWarnings("hiding") PExp4 _left_,
        @SuppressWarnings("hiding") TELogico _eLogico_,
        @SuppressWarnings("hiding") PExp5 _right_)
    {
        // Constructor
        setLeft(_left_);

        setELogico(_eLogico_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new AAndExp4(
            cloneNode(this._left_),
            cloneNode(this._eLogico_),
            cloneNode(this._right_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAndExp4(this);
    }

    public PExp4 getLeft()
    {
        return this._left_;
    }

    public void setLeft(PExp4 node)
    {
        if(this._left_ != null)
        {
            this._left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._left_ = node;
    }

    public TELogico getELogico()
    {
        return this._eLogico_;
    }

    public void setELogico(TELogico node)
    {
        if(this._eLogico_ != null)
        {
            this._eLogico_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._eLogico_ = node;
    }

    public PExp5 getRight()
    {
        return this._right_;
    }

    public void setRight(PExp5 node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._left_)
            + toString(this._eLogico_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._left_ == child)
        {
            this._left_ = null;
            return;
        }

        if(this._eLogico_ == child)
        {
            this._eLogico_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._left_ == oldChild)
        {
            setLeft((PExp4) newChild);
            return;
        }

        if(this._eLogico_ == oldChild)
        {
            setELogico((TELogico) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((PExp5) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
