/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class AAtributoExp extends PExp
{
    private PIdPontoAux _idPontoAux_;
    private PAtributos _atributos_;
    private TPontoVirg _pontoVirg_;

    public AAtributoExp()
    {
        // Constructor
    }

    public AAtributoExp(
        @SuppressWarnings("hiding") PIdPontoAux _idPontoAux_,
        @SuppressWarnings("hiding") PAtributos _atributos_,
        @SuppressWarnings("hiding") TPontoVirg _pontoVirg_)
    {
        // Constructor
        setIdPontoAux(_idPontoAux_);

        setAtributos(_atributos_);

        setPontoVirg(_pontoVirg_);

    }

    @Override
    public Object clone()
    {
        return new AAtributoExp(
            cloneNode(this._idPontoAux_),
            cloneNode(this._atributos_),
            cloneNode(this._pontoVirg_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAtributoExp(this);
    }

    public PIdPontoAux getIdPontoAux()
    {
        return this._idPontoAux_;
    }

    public void setIdPontoAux(PIdPontoAux node)
    {
        if(this._idPontoAux_ != null)
        {
            this._idPontoAux_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._idPontoAux_ = node;
    }

    public PAtributos getAtributos()
    {
        return this._atributos_;
    }

    public void setAtributos(PAtributos node)
    {
        if(this._atributos_ != null)
        {
            this._atributos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._atributos_ = node;
    }

    public TPontoVirg getPontoVirg()
    {
        return this._pontoVirg_;
    }

    public void setPontoVirg(TPontoVirg node)
    {
        if(this._pontoVirg_ != null)
        {
            this._pontoVirg_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pontoVirg_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._idPontoAux_)
            + toString(this._atributos_)
            + toString(this._pontoVirg_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._idPontoAux_ == child)
        {
            this._idPontoAux_ = null;
            return;
        }

        if(this._atributos_ == child)
        {
            this._atributos_ = null;
            return;
        }

        if(this._pontoVirg_ == child)
        {
            this._pontoVirg_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._idPontoAux_ == oldChild)
        {
            setIdPontoAux((PIdPontoAux) newChild);
            return;
        }

        if(this._atributos_ == oldChild)
        {
            setAtributos((PAtributos) newChild);
            return;
        }

        if(this._pontoVirg_ == oldChild)
        {
            setPontoVirg((TPontoVirg) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
