/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import java.util.*;
import quase.analysis.*;

@SuppressWarnings("nls")
public final class ABlocoExp extends PBlocoExp
{
    private TComeca _comeca_;
    private final LinkedList<PDecCons> _decCons_ = new LinkedList<PDecCons>();
    private PExp _exp_;
    private TTermina _termina_;

    public ABlocoExp()
    {
        // Constructor
    }

    public ABlocoExp(
        @SuppressWarnings("hiding") TComeca _comeca_,
        @SuppressWarnings("hiding") List<?> _decCons_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TTermina _termina_)
    {
        // Constructor
        setComeca(_comeca_);

        setDecCons(_decCons_);

        setExp(_exp_);

        setTermina(_termina_);

    }

    @Override
    public Object clone()
    {
        return new ABlocoExp(
            cloneNode(this._comeca_),
            cloneList(this._decCons_),
            cloneNode(this._exp_),
            cloneNode(this._termina_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABlocoExp(this);
    }

    public TComeca getComeca()
    {
        return this._comeca_;
    }

    public void setComeca(TComeca node)
    {
        if(this._comeca_ != null)
        {
            this._comeca_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comeca_ = node;
    }

    public LinkedList<PDecCons> getDecCons()
    {
        return this._decCons_;
    }

    public void setDecCons(List<?> list)
    {
        for(PDecCons e : this._decCons_)
        {
            e.parent(null);
        }
        this._decCons_.clear();

        for(Object obj_e : list)
        {
            PDecCons e = (PDecCons) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._decCons_.add(e);
        }
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TTermina getTermina()
    {
        return this._termina_;
    }

    public void setTermina(TTermina node)
    {
        if(this._termina_ != null)
        {
            this._termina_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termina_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comeca_)
            + toString(this._decCons_)
            + toString(this._exp_)
            + toString(this._termina_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comeca_ == child)
        {
            this._comeca_ = null;
            return;
        }

        if(this._decCons_.remove(child))
        {
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._termina_ == child)
        {
            this._termina_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comeca_ == oldChild)
        {
            setComeca((TComeca) newChild);
            return;
        }

        for(ListIterator<PDecCons> i = this._decCons_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PDecCons) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._termina_ == oldChild)
        {
            setTermina((TTermina) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
