/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class ABoolTipoPrimitivo extends PTipoPrimitivo
{
    private TBoolTipo _boolTipo_;

    public ABoolTipoPrimitivo()
    {
        // Constructor
    }

    public ABoolTipoPrimitivo(
        @SuppressWarnings("hiding") TBoolTipo _boolTipo_)
    {
        // Constructor
        setBoolTipo(_boolTipo_);

    }

    @Override
    public Object clone()
    {
        return new ABoolTipoPrimitivo(
            cloneNode(this._boolTipo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABoolTipoPrimitivo(this);
    }

    public TBoolTipo getBoolTipo()
    {
        return this._boolTipo_;
    }

    public void setBoolTipo(TBoolTipo node)
    {
        if(this._boolTipo_ != null)
        {
            this._boolTipo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._boolTipo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._boolTipo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._boolTipo_ == child)
        {
            this._boolTipo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._boolTipo_ == oldChild)
        {
            setBoolTipo((TBoolTipo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
