/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class AChamadaExp6 extends PExp6
{
    private PIdPontoAux _idPontoAux_;
    private PChamada _chamada_;

    public AChamadaExp6()
    {
        // Constructor
    }

    public AChamadaExp6(
        @SuppressWarnings("hiding") PIdPontoAux _idPontoAux_,
        @SuppressWarnings("hiding") PChamada _chamada_)
    {
        // Constructor
        setIdPontoAux(_idPontoAux_);

        setChamada(_chamada_);

    }

    @Override
    public Object clone()
    {
        return new AChamadaExp6(
            cloneNode(this._idPontoAux_),
            cloneNode(this._chamada_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAChamadaExp6(this);
    }

    public PIdPontoAux getIdPontoAux()
    {
        return this._idPontoAux_;
    }

    public void setIdPontoAux(PIdPontoAux node)
    {
        if(this._idPontoAux_ != null)
        {
            this._idPontoAux_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._idPontoAux_ = node;
    }

    public PChamada getChamada()
    {
        return this._chamada_;
    }

    public void setChamada(PChamada node)
    {
        if(this._chamada_ != null)
        {
            this._chamada_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._chamada_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._idPontoAux_)
            + toString(this._chamada_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._idPontoAux_ == child)
        {
            this._idPontoAux_ = null;
            return;
        }

        if(this._chamada_ == child)
        {
            this._chamada_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._idPontoAux_ == oldChild)
        {
            setIdPontoAux((PIdPontoAux) newChild);
            return;
        }

        if(this._chamada_ == oldChild)
        {
            setChamada((PChamada) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
