/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class AComando3Comando2 extends PComando2
{
    private PComando3 _comando3_;

    public AComando3Comando2()
    {
        // Constructor
    }

    public AComando3Comando2(
        @SuppressWarnings("hiding") PComando3 _comando3_)
    {
        // Constructor
        setComando3(_comando3_);

    }

    @Override
    public Object clone()
    {
        return new AComando3Comando2(
            cloneNode(this._comando3_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComando3Comando2(this);
    }

    public PComando3 getComando3()
    {
        return this._comando3_;
    }

    public void setComando3(PComando3 node)
    {
        if(this._comando3_ != null)
        {
            this._comando3_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comando3_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comando3_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comando3_ == child)
        {
            this._comando3_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comando3_ == oldChild)
        {
            setComando3((PComando3) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
