/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class AComando1Comando extends PComando
{
    private PComando1 _comando1_;

    public AComando1Comando()
    {
        // Constructor
    }

    public AComando1Comando(
        @SuppressWarnings("hiding") PComando1 _comando1_)
    {
        // Constructor
        setComando1(_comando1_);

    }

    @Override
    public Object clone()
    {
        return new AComando1Comando(
            cloneNode(this._comando1_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComando1Comando(this);
    }

    public PComando1 getComando1()
    {
        return this._comando1_;
    }

    public void setComando1(PComando1 node)
    {
        if(this._comando1_ != null)
        {
            this._comando1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comando1_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comando1_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comando1_ == child)
        {
            this._comando1_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comando1_ == oldChild)
        {
            setComando1((PComando1) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
