/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import java.util.*;
import quase.analysis.*;

@SuppressWarnings("nls")
public final class ADecFuncaoMetodos extends PMetodos
{
    private final LinkedList<PDecFuncao> _decFuncao_ = new LinkedList<PDecFuncao>();

    public ADecFuncaoMetodos()
    {
        // Constructor
    }

    public ADecFuncaoMetodos(
        @SuppressWarnings("hiding") List<?> _decFuncao_)
    {
        // Constructor
        setDecFuncao(_decFuncao_);

    }

    @Override
    public Object clone()
    {
        return new ADecFuncaoMetodos(
            cloneList(this._decFuncao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecFuncaoMetodos(this);
    }

    public LinkedList<PDecFuncao> getDecFuncao()
    {
        return this._decFuncao_;
    }

    public void setDecFuncao(List<?> list)
    {
        for(PDecFuncao e : this._decFuncao_)
        {
            e.parent(null);
        }
        this._decFuncao_.clear();

        for(Object obj_e : list)
        {
            PDecFuncao e = (PDecFuncao) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._decFuncao_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._decFuncao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._decFuncao_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PDecFuncao> i = this._decFuncao_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PDecFuncao) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
