/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import java.util.*;
import quase.analysis.*;

@SuppressWarnings("nls")
public final class ADecObj extends PDecObj
{
    private TObj _obj_;
    private TCid _cid_;
    private TId _id_;
    private final LinkedList<PVirgIdAux> _virgIdAux_ = new LinkedList<PVirgIdAux>();
    private TPontoVirg _pontoVirg_;

    public ADecObj()
    {
        // Constructor
    }

    public ADecObj(
        @SuppressWarnings("hiding") TObj _obj_,
        @SuppressWarnings("hiding") TCid _cid_,
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") List<?> _virgIdAux_,
        @SuppressWarnings("hiding") TPontoVirg _pontoVirg_)
    {
        // Constructor
        setObj(_obj_);

        setCid(_cid_);

        setId(_id_);

        setVirgIdAux(_virgIdAux_);

        setPontoVirg(_pontoVirg_);

    }

    @Override
    public Object clone()
    {
        return new ADecObj(
            cloneNode(this._obj_),
            cloneNode(this._cid_),
            cloneNode(this._id_),
            cloneList(this._virgIdAux_),
            cloneNode(this._pontoVirg_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecObj(this);
    }

    public TObj getObj()
    {
        return this._obj_;
    }

    public void setObj(TObj node)
    {
        if(this._obj_ != null)
        {
            this._obj_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._obj_ = node;
    }

    public TCid getCid()
    {
        return this._cid_;
    }

    public void setCid(TCid node)
    {
        if(this._cid_ != null)
        {
            this._cid_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cid_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public LinkedList<PVirgIdAux> getVirgIdAux()
    {
        return this._virgIdAux_;
    }

    public void setVirgIdAux(List<?> list)
    {
        for(PVirgIdAux e : this._virgIdAux_)
        {
            e.parent(null);
        }
        this._virgIdAux_.clear();

        for(Object obj_e : list)
        {
            PVirgIdAux e = (PVirgIdAux) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._virgIdAux_.add(e);
        }
    }

    public TPontoVirg getPontoVirg()
    {
        return this._pontoVirg_;
    }

    public void setPontoVirg(TPontoVirg node)
    {
        if(this._pontoVirg_ != null)
        {
            this._pontoVirg_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pontoVirg_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._obj_)
            + toString(this._cid_)
            + toString(this._id_)
            + toString(this._virgIdAux_)
            + toString(this._pontoVirg_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._obj_ == child)
        {
            this._obj_ = null;
            return;
        }

        if(this._cid_ == child)
        {
            this._cid_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._virgIdAux_.remove(child))
        {
            return;
        }

        if(this._pontoVirg_ == child)
        {
            this._pontoVirg_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._obj_ == oldChild)
        {
            setObj((TObj) newChild);
            return;
        }

        if(this._cid_ == oldChild)
        {
            setCid((TCid) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        for(ListIterator<PVirgIdAux> i = this._virgIdAux_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PVirgIdAux) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._pontoVirg_ == oldChild)
        {
            setPontoVirg((TPontoVirg) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
