/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import java.util.*;
import quase.analysis.*;

@SuppressWarnings("nls")
public final class ADecObjAtributos extends PAtributos
{
    private final LinkedList<PDecObj> _decObj_ = new LinkedList<PDecObj>();

    public ADecObjAtributos()
    {
        // Constructor
    }

    public ADecObjAtributos(
        @SuppressWarnings("hiding") List<?> _decObj_)
    {
        // Constructor
        setDecObj(_decObj_);

    }

    @Override
    public Object clone()
    {
        return new ADecObjAtributos(
            cloneList(this._decObj_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecObjAtributos(this);
    }

    public LinkedList<PDecObj> getDecObj()
    {
        return this._decObj_;
    }

    public void setDecObj(List<?> list)
    {
        for(PDecObj e : this._decObj_)
        {
            e.parent(null);
        }
        this._decObj_.clear();

        for(Object obj_e : list)
        {
            PDecObj e = (PDecObj) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._decObj_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._decObj_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._decObj_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PDecObj> i = this._decObj_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PDecObj) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
