/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class AFalseExp6 extends PExp6
{
    private TBoolFalso _boolFalso_;

    public AFalseExp6()
    {
        // Constructor
    }

    public AFalseExp6(
        @SuppressWarnings("hiding") TBoolFalso _boolFalso_)
    {
        // Constructor
        setBoolFalso(_boolFalso_);

    }

    @Override
    public Object clone()
    {
        return new AFalseExp6(
            cloneNode(this._boolFalso_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFalseExp6(this);
    }

    public TBoolFalso getBoolFalso()
    {
        return this._boolFalso_;
    }

    public void setBoolFalso(TBoolFalso node)
    {
        if(this._boolFalso_ != null)
        {
            this._boolFalso_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._boolFalso_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._boolFalso_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._boolFalso_ == child)
        {
            this._boolFalso_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._boolFalso_ == oldChild)
        {
            setBoolFalso((TBoolFalso) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
