/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class AFamiliaAux extends PFamiliaAux
{
    private TEComercial _eComercial_;
    private PRelacao _relacao_;

    public AFamiliaAux()
    {
        // Constructor
    }

    public AFamiliaAux(
        @SuppressWarnings("hiding") TEComercial _eComercial_,
        @SuppressWarnings("hiding") PRelacao _relacao_)
    {
        // Constructor
        setEComercial(_eComercial_);

        setRelacao(_relacao_);

    }

    @Override
    public Object clone()
    {
        return new AFamiliaAux(
            cloneNode(this._eComercial_),
            cloneNode(this._relacao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFamiliaAux(this);
    }

    public TEComercial getEComercial()
    {
        return this._eComercial_;
    }

    public void setEComercial(TEComercial node)
    {
        if(this._eComercial_ != null)
        {
            this._eComercial_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._eComercial_ = node;
    }

    public PRelacao getRelacao()
    {
        return this._relacao_;
    }

    public void setRelacao(PRelacao node)
    {
        if(this._relacao_ != null)
        {
            this._relacao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._relacao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._eComercial_)
            + toString(this._relacao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._eComercial_ == child)
        {
            this._eComercial_ = null;
            return;
        }

        if(this._relacao_ == child)
        {
            this._relacao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._eComercial_ == oldChild)
        {
            setEComercial((TEComercial) newChild);
            return;
        }

        if(this._relacao_ == oldChild)
        {
            setRelacao((PRelacao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
