/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class AIgualExp3 extends PExp3
{
    private PExp3 _left_;
    private TIgualComp _igualComp_;
    private PExp4 _right_;

    public AIgualExp3()
    {
        // Constructor
    }

    public AIgualExp3(
        @SuppressWarnings("hiding") PExp3 _left_,
        @SuppressWarnings("hiding") TIgualComp _igualComp_,
        @SuppressWarnings("hiding") PExp4 _right_)
    {
        // Constructor
        setLeft(_left_);

        setIgualComp(_igualComp_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new AIgualExp3(
            cloneNode(this._left_),
            cloneNode(this._igualComp_),
            cloneNode(this._right_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIgualExp3(this);
    }

    public PExp3 getLeft()
    {
        return this._left_;
    }

    public void setLeft(PExp3 node)
    {
        if(this._left_ != null)
        {
            this._left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._left_ = node;
    }

    public TIgualComp getIgualComp()
    {
        return this._igualComp_;
    }

    public void setIgualComp(TIgualComp node)
    {
        if(this._igualComp_ != null)
        {
            this._igualComp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._igualComp_ = node;
    }

    public PExp4 getRight()
    {
        return this._right_;
    }

    public void setRight(PExp4 node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._left_)
            + toString(this._igualComp_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._left_ == child)
        {
            this._left_ = null;
            return;
        }

        if(this._igualComp_ == child)
        {
            this._igualComp_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._left_ == oldChild)
        {
            setLeft((PExp3) newChild);
            return;
        }

        if(this._igualComp_ == oldChild)
        {
            setIgualComp((TIgualComp) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((PExp4) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
