/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class AIntTipoPrimitivo extends PTipoPrimitivo
{
    private TIntTipo _intTipo_;

    public AIntTipoPrimitivo()
    {
        // Constructor
    }

    public AIntTipoPrimitivo(
        @SuppressWarnings("hiding") TIntTipo _intTipo_)
    {
        // Constructor
        setIntTipo(_intTipo_);

    }

    @Override
    public Object clone()
    {
        return new AIntTipoPrimitivo(
            cloneNode(this._intTipo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIntTipoPrimitivo(this);
    }

    public TIntTipo getIntTipo()
    {
        return this._intTipo_;
    }

    public void setIntTipo(TIntTipo node)
    {
        if(this._intTipo_ != null)
        {
            this._intTipo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._intTipo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._intTipo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._intTipo_ == child)
        {
            this._intTipo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._intTipo_ == oldChild)
        {
            setIntTipo((TIntTipo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
