/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class AListaExpComListaExp extends PListaExp
{
    private PExp _exp_;
    private PListaExpCom _listaExpCom_;

    public AListaExpComListaExp()
    {
        // Constructor
    }

    public AListaExpComListaExp(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") PListaExpCom _listaExpCom_)
    {
        // Constructor
        setExp(_exp_);

        setListaExpCom(_listaExpCom_);

    }

    @Override
    public Object clone()
    {
        return new AListaExpComListaExp(
            cloneNode(this._exp_),
            cloneNode(this._listaExpCom_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaExpComListaExp(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public PListaExpCom getListaExpCom()
    {
        return this._listaExpCom_;
    }

    public void setListaExpCom(PListaExpCom node)
    {
        if(this._listaExpCom_ != null)
        {
            this._listaExpCom_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaExpCom_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._listaExpCom_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._listaExpCom_ == child)
        {
            this._listaExpCom_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._listaExpCom_ == oldChild)
        {
            setListaExpCom((PListaExpCom) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
