/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import java.util.*;
import quase.analysis.*;

@SuppressWarnings("nls")
public final class AMetodos extends PMetodos
{
    private final LinkedList<PMetodosAux> _metodosAux_ = new LinkedList<PMetodosAux>();

    public AMetodos()
    {
        // Constructor
    }

    public AMetodos(
        @SuppressWarnings("hiding") List<?> _metodosAux_)
    {
        // Constructor
        setMetodosAux(_metodosAux_);

    }

    @Override
    public Object clone()
    {
        return new AMetodos(
            cloneList(this._metodosAux_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMetodos(this);
    }

    public LinkedList<PMetodosAux> getMetodosAux()
    {
        return this._metodosAux_;
    }

    public void setMetodosAux(List<?> list)
    {
        for(PMetodosAux e : this._metodosAux_)
        {
            e.parent(null);
        }
        this._metodosAux_.clear();

        for(Object obj_e : list)
        {
            PMetodosAux e = (PMetodosAux) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._metodosAux_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._metodosAux_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._metodosAux_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PMetodosAux> i = this._metodosAux_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PMetodosAux) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
