/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import java.util.*;
import quase.analysis.*;

@SuppressWarnings("nls")
public final class AParametrosParametros extends PParametros
{
    private PParametro _parametro_;
    private final LinkedList<PVirgParametroAux> _virgParametroAux_ = new LinkedList<PVirgParametroAux>();

    public AParametrosParametros()
    {
        // Constructor
    }

    public AParametrosParametros(
        @SuppressWarnings("hiding") PParametro _parametro_,
        @SuppressWarnings("hiding") List<?> _virgParametroAux_)
    {
        // Constructor
        setParametro(_parametro_);

        setVirgParametroAux(_virgParametroAux_);

    }

    @Override
    public Object clone()
    {
        return new AParametrosParametros(
            cloneNode(this._parametro_),
            cloneList(this._virgParametroAux_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParametrosParametros(this);
    }

    public PParametro getParametro()
    {
        return this._parametro_;
    }

    public void setParametro(PParametro node)
    {
        if(this._parametro_ != null)
        {
            this._parametro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parametro_ = node;
    }

    public LinkedList<PVirgParametroAux> getVirgParametroAux()
    {
        return this._virgParametroAux_;
    }

    public void setVirgParametroAux(List<?> list)
    {
        for(PVirgParametroAux e : this._virgParametroAux_)
        {
            e.parent(null);
        }
        this._virgParametroAux_.clear();

        for(Object obj_e : list)
        {
            PVirgParametroAux e = (PVirgParametroAux) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._virgParametroAux_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._parametro_)
            + toString(this._virgParametroAux_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._parametro_ == child)
        {
            this._parametro_ = null;
            return;
        }

        if(this._virgParametroAux_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._parametro_ == oldChild)
        {
            setParametro((PParametro) newChild);
            return;
        }

        for(ListIterator<PVirgParametroAux> i = this._virgParametroAux_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PVirgParametroAux) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
