/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class ARealTipoPrimitivo extends PTipoPrimitivo
{
    private TRealTipo _realTipo_;

    public ARealTipoPrimitivo()
    {
        // Constructor
    }

    public ARealTipoPrimitivo(
        @SuppressWarnings("hiding") TRealTipo _realTipo_)
    {
        // Constructor
        setRealTipo(_realTipo_);

    }

    @Override
    public Object clone()
    {
        return new ARealTipoPrimitivo(
            cloneNode(this._realTipo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARealTipoPrimitivo(this);
    }

    public TRealTipo getRealTipo()
    {
        return this._realTipo_;
    }

    public void setRealTipo(TRealTipo node)
    {
        if(this._realTipo_ != null)
        {
            this._realTipo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._realTipo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._realTipo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._realTipo_ == child)
        {
            this._realTipo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._realTipo_ == oldChild)
        {
            setRealTipo((TRealTipo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
