/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class ARelacaoRelacao extends PRelacao
{
    private TClasse _classe_;
    private TCid _left_;
    private TFilhaClasse _filhaClasse_;
    private TCid _right_;

    public ARelacaoRelacao()
    {
        // Constructor
    }

    public ARelacaoRelacao(
        @SuppressWarnings("hiding") TClasse _classe_,
        @SuppressWarnings("hiding") TCid _left_,
        @SuppressWarnings("hiding") TFilhaClasse _filhaClasse_,
        @SuppressWarnings("hiding") TCid _right_)
    {
        // Constructor
        setClasse(_classe_);

        setLeft(_left_);

        setFilhaClasse(_filhaClasse_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new ARelacaoRelacao(
            cloneNode(this._classe_),
            cloneNode(this._left_),
            cloneNode(this._filhaClasse_),
            cloneNode(this._right_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARelacaoRelacao(this);
    }

    public TClasse getClasse()
    {
        return this._classe_;
    }

    public void setClasse(TClasse node)
    {
        if(this._classe_ != null)
        {
            this._classe_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._classe_ = node;
    }

    public TCid getLeft()
    {
        return this._left_;
    }

    public void setLeft(TCid node)
    {
        if(this._left_ != null)
        {
            this._left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._left_ = node;
    }

    public TFilhaClasse getFilhaClasse()
    {
        return this._filhaClasse_;
    }

    public void setFilhaClasse(TFilhaClasse node)
    {
        if(this._filhaClasse_ != null)
        {
            this._filhaClasse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._filhaClasse_ = node;
    }

    public TCid getRight()
    {
        return this._right_;
    }

    public void setRight(TCid node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._classe_)
            + toString(this._left_)
            + toString(this._filhaClasse_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._classe_ == child)
        {
            this._classe_ = null;
            return;
        }

        if(this._left_ == child)
        {
            this._left_ = null;
            return;
        }

        if(this._filhaClasse_ == child)
        {
            this._filhaClasse_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._classe_ == oldChild)
        {
            setClasse((TClasse) newChild);
            return;
        }

        if(this._left_ == oldChild)
        {
            setLeft((TCid) newChild);
            return;
        }

        if(this._filhaClasse_ == oldChild)
        {
            setFilhaClasse((TFilhaClasse) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((TCid) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
