/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class ASubtOpExp extends POpExp
{
    private TSubt _subt_;

    public ASubtOpExp()
    {
        // Constructor
    }

    public ASubtOpExp(
        @SuppressWarnings("hiding") TSubt _subt_)
    {
        // Constructor
        setSubt(_subt_);

    }

    @Override
    public Object clone()
    {
        return new ASubtOpExp(
            cloneNode(this._subt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASubtOpExp(this);
    }

    public TSubt getSubt()
    {
        return this._subt_;
    }

    public void setSubt(TSubt node)
    {
        if(this._subt_ != null)
        {
            this._subt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._subt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._subt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._subt_ == child)
        {
            this._subt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._subt_ == oldChild)
        {
            setSubt((TSubt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
