/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class ASubtPartExp extends PExp
{
    private TSubt _subt_;
    private PExp _exp_;
    private PExp1 _exp1_;

    public ASubtPartExp()
    {
        // Constructor
    }

    public ASubtPartExp(
        @SuppressWarnings("hiding") TSubt _subt_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") PExp1 _exp1_)
    {
        // Constructor
        setSubt(_subt_);

        setExp(_exp_);

        setExp1(_exp1_);

    }

    @Override
    public Object clone()
    {
        return new ASubtPartExp(
            cloneNode(this._subt_),
            cloneNode(this._exp_),
            cloneNode(this._exp1_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASubtPartExp(this);
    }

    public TSubt getSubt()
    {
        return this._subt_;
    }

    public void setSubt(TSubt node)
    {
        if(this._subt_ != null)
        {
            this._subt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._subt_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public PExp1 getExp1()
    {
        return this._exp1_;
    }

    public void setExp1(PExp1 node)
    {
        if(this._exp1_ != null)
        {
            this._exp1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp1_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._subt_)
            + toString(this._exp_)
            + toString(this._exp1_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._subt_ == child)
        {
            this._subt_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._exp1_ == child)
        {
            this._exp1_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._subt_ == oldChild)
        {
            setSubt((TSubt) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._exp1_ == oldChild)
        {
            setExp1((PExp1) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
