/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class ASubtTesteTeste extends PTeste
{
    private TSubt _subt_;
    private PTeste _teste_;

    public ASubtTesteTeste()
    {
        // Constructor
    }

    public ASubtTesteTeste(
        @SuppressWarnings("hiding") TSubt _subt_,
        @SuppressWarnings("hiding") PTeste _teste_)
    {
        // Constructor
        setSubt(_subt_);

        setTeste(_teste_);

    }

    @Override
    public Object clone()
    {
        return new ASubtTesteTeste(
            cloneNode(this._subt_),
            cloneNode(this._teste_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASubtTesteTeste(this);
    }

    public TSubt getSubt()
    {
        return this._subt_;
    }

    public void setSubt(TSubt node)
    {
        if(this._subt_ != null)
        {
            this._subt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._subt_ = node;
    }

    public PTeste getTeste()
    {
        return this._teste_;
    }

    public void setTeste(PTeste node)
    {
        if(this._teste_ != null)
        {
            this._teste_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._teste_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._subt_)
            + toString(this._teste_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._subt_ == child)
        {
            this._subt_ = null;
            return;
        }

        if(this._teste_ == child)
        {
            this._teste_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._subt_ == oldChild)
        {
            setSubt((TSubt) newChild);
            return;
        }

        if(this._teste_ == oldChild)
        {
            setTeste((PTeste) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
