/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class ATipoClasse extends PTipoClasse
{
    private TCid _cid_;

    public ATipoClasse()
    {
        // Constructor
    }

    public ATipoClasse(
        @SuppressWarnings("hiding") TCid _cid_)
    {
        // Constructor
        setCid(_cid_);

    }

    @Override
    public Object clone()
    {
        return new ATipoClasse(
            cloneNode(this._cid_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATipoClasse(this);
    }

    public TCid getCid()
    {
        return this._cid_;
    }

    public void setCid(TCid node)
    {
        if(this._cid_ != null)
        {
            this._cid_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cid_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cid_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cid_ == child)
        {
            this._cid_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cid_ == oldChild)
        {
            setCid((TCid) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
