/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class ATipoClasseTipo extends PTipo
{
    private PTipoClasse _tipoClasse_;

    public ATipoClasseTipo()
    {
        // Constructor
    }

    public ATipoClasseTipo(
        @SuppressWarnings("hiding") PTipoClasse _tipoClasse_)
    {
        // Constructor
        setTipoClasse(_tipoClasse_);

    }

    @Override
    public Object clone()
    {
        return new ATipoClasseTipo(
            cloneNode(this._tipoClasse_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATipoClasseTipo(this);
    }

    public PTipoClasse getTipoClasse()
    {
        return this._tipoClasse_;
    }

    public void setTipoClasse(PTipoClasse node)
    {
        if(this._tipoClasse_ != null)
        {
            this._tipoClasse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipoClasse_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tipoClasse_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tipoClasse_ == child)
        {
            this._tipoClasse_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tipoClasse_ == oldChild)
        {
            setTipoClasse((PTipoClasse) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
