/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class ATrueExp extends PExp
{
    private TBoolVerdadeiro _boolVerdadeiro_;

    public ATrueExp()
    {
        // Constructor
    }

    public ATrueExp(
        @SuppressWarnings("hiding") TBoolVerdadeiro _boolVerdadeiro_)
    {
        // Constructor
        setBoolVerdadeiro(_boolVerdadeiro_);

    }

    @Override
    public Object clone()
    {
        return new ATrueExp(
            cloneNode(this._boolVerdadeiro_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATrueExp(this);
    }

    public TBoolVerdadeiro getBoolVerdadeiro()
    {
        return this._boolVerdadeiro_;
    }

    public void setBoolVerdadeiro(TBoolVerdadeiro node)
    {
        if(this._boolVerdadeiro_ != null)
        {
            this._boolVerdadeiro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._boolVerdadeiro_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._boolVerdadeiro_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._boolVerdadeiro_ == child)
        {
            this._boolVerdadeiro_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._boolVerdadeiro_ == oldChild)
        {
            setBoolVerdadeiro((TBoolVerdadeiro) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
