/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class AVirgInicializacaoVirgInicializacaoAux extends PVirgInicializacaoAux
{
    private TVirg _virg_;
    private PInicializacao _inicializacao_;

    public AVirgInicializacaoVirgInicializacaoAux()
    {
        // Constructor
    }

    public AVirgInicializacaoVirgInicializacaoAux(
        @SuppressWarnings("hiding") TVirg _virg_,
        @SuppressWarnings("hiding") PInicializacao _inicializacao_)
    {
        // Constructor
        setVirg(_virg_);

        setInicializacao(_inicializacao_);

    }

    @Override
    public Object clone()
    {
        return new AVirgInicializacaoVirgInicializacaoAux(
            cloneNode(this._virg_),
            cloneNode(this._inicializacao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVirgInicializacaoVirgInicializacaoAux(this);
    }

    public TVirg getVirg()
    {
        return this._virg_;
    }

    public void setVirg(TVirg node)
    {
        if(this._virg_ != null)
        {
            this._virg_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._virg_ = node;
    }

    public PInicializacao getInicializacao()
    {
        return this._inicializacao_;
    }

    public void setInicializacao(PInicializacao node)
    {
        if(this._inicializacao_ != null)
        {
            this._inicializacao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inicializacao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._virg_)
            + toString(this._inicializacao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._virg_ == child)
        {
            this._virg_ = null;
            return;
        }

        if(this._inicializacao_ == child)
        {
            this._inicializacao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._virg_ == oldChild)
        {
            setVirg((TVirg) newChild);
            return;
        }

        if(this._inicializacao_ == oldChild)
        {
            setInicializacao((PInicializacao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
