/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class TClasse extends Token
{
    public TClasse()
    {
        super.setText("classe");
    }

    public TClasse(int line, int pos)
    {
        super.setText("classe");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TClasse(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTClasse(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TClasse text.");
    }
}
