/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class TFilhaClasse extends Token
{
    public TFilhaClasse()
    {
        super.setText("filha da classe");
    }

    public TFilhaClasse(int line, int pos)
    {
        super.setText("filha da classe");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFilhaClasse(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFilhaClasse(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFilhaClasse text.");
    }
}
