/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.node;

import quase.analysis.*;

@SuppressWarnings("nls")
public final class TFunc extends Token
{
    public TFunc()
    {
        super.setText("função");
    }

    public TFunc(int line, int pos)
    {
        super.setText("função");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFunc(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFunc(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFunc text.");
    }
}
