/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.analysis;

import quase.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseAExp(AExp node);
    void caseASubtPartExp(ASubtPartExp node);
    void caseAAdcExp(AAdcExp node);
    void caseASubtPartExp1(ASubtPartExp1 node);
    void caseAAdcExp1(AAdcExp1 node);

    void caseTEComercial(TEComercial node);
    void caseTPontoVirg(TPontoVirg node);
    void caseTClasse(TClasse node);
    void caseTFilhaClasse(TFilhaClasse node);
    void caseTComeca(TComeca node);
    void caseTTermina(TTermina node);
    void caseTObj(TObj node);
    void caseTVirg(TVirg node);
    void caseTVar(TVar node);
    void caseTCons(TCons node);
    void caseTAtr(TAtr node);
    void caseTIntTipo(TIntTipo node);
    void caseTBoolTipo(TBoolTipo node);
    void caseTRealTipo(TRealTipo node);
    void caseTDetProcInicial(TDetProcInicial node);
    void caseTProc(TProc node);
    void caseTParEsq(TParEsq node);
    void caseTParDir(TParDir node);
    void caseTFunc(TFunc node);
    void caseTSe(TSe node);
    void caseTSenao(TSenao node);
    void caseTEnquanto(TEnquanto node);
    void caseTIgualSimples(TIgualSimples node);
    void caseTPonto(TPonto node);
    void caseTBoolVerdadeiro(TBoolVerdadeiro node);
    void caseTBoolFalso(TBoolFalso node);
    void caseTSubt(TSubt node);
    void caseTEntao(TEntao node);
    void caseTAdc(TAdc node);
    void caseTMult(TMult node);
    void caseTDiv(TDiv node);
    void caseTMod(TMod node);
    void caseTIgualComp(TIgualComp node);
    void caseTMenor(TMenor node);
    void caseTNao(TNao node);
    void caseTELogico(TELogico node);
    void caseTOuLogico(TOuLogico node);
    void caseTComentario(TComentario node);
    void caseTId(TId node);
    void caseTCid(TCid node);
    void caseTVazio(TVazio node);
    void caseTNumInteiro(TNumInteiro node);
    void caseTNumReal(TNumReal node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
