/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.analysis;

import java.util.*;
import quase.node.*;

public class ReversedDepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getEOF().apply(this);
        node.getPExp().apply(this);
        outStart(node);
    }

    public void inAExp(AExp node)
    {
        defaultIn(node);
    }

    public void outAExp(AExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExp(AExp node)
    {
        inAExp(node);
        if(node.getExp1() != null)
        {
            node.getExp1().apply(this);
        }
        outAExp(node);
    }

    public void inASubtPartExp(ASubtPartExp node)
    {
        defaultIn(node);
    }

    public void outASubtPartExp(ASubtPartExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASubtPartExp(ASubtPartExp node)
    {
        inASubtPartExp(node);
        if(node.getExp1() != null)
        {
            node.getExp1().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getSubt() != null)
        {
            node.getSubt().apply(this);
        }
        outASubtPartExp(node);
    }

    public void inAAdcExp(AAdcExp node)
    {
        defaultIn(node);
    }

    public void outAAdcExp(AAdcExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAdcExp(AAdcExp node)
    {
        inAAdcExp(node);
        if(node.getExp1() != null)
        {
            node.getExp1().apply(this);
        }
        if(node.getLeft() != null)
        {
            node.getLeft().apply(this);
        }
        outAAdcExp(node);
    }

    public void inASubtPartExp1(ASubtPartExp1 node)
    {
        defaultIn(node);
    }

    public void outASubtPartExp1(ASubtPartExp1 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASubtPartExp1(ASubtPartExp1 node)
    {
        inASubtPartExp1(node);
        outASubtPartExp1(node);
    }

    public void inAAdcExp1(AAdcExp1 node)
    {
        defaultIn(node);
    }

    public void outAAdcExp1(AAdcExp1 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAdcExp1(AAdcExp1 node)
    {
        inAAdcExp1(node);
        if(node.getRight() != null)
        {
            node.getRight().apply(this);
        }
        if(node.getAdc() != null)
        {
            node.getAdc().apply(this);
        }
        outAAdcExp1(node);
    }
}
