/* This file was generated by SableCC (http://www.sablecc.org/). */

package quase.parser;

import quase.node.*;
import quase.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTEComercial(@SuppressWarnings("unused") TEComercial node)
    {
        this.index = 0;
    }

    @Override
    public void caseTPontoVirg(@SuppressWarnings("unused") TPontoVirg node)
    {
        this.index = 1;
    }

    @Override
    public void caseTClasse(@SuppressWarnings("unused") TClasse node)
    {
        this.index = 2;
    }

    @Override
    public void caseTFilhaClasse(@SuppressWarnings("unused") TFilhaClasse node)
    {
        this.index = 3;
    }

    @Override
    public void caseTComeca(@SuppressWarnings("unused") TComeca node)
    {
        this.index = 4;
    }

    @Override
    public void caseTTermina(@SuppressWarnings("unused") TTermina node)
    {
        this.index = 5;
    }

    @Override
    public void caseTObj(@SuppressWarnings("unused") TObj node)
    {
        this.index = 6;
    }

    @Override
    public void caseTVirg(@SuppressWarnings("unused") TVirg node)
    {
        this.index = 7;
    }

    @Override
    public void caseTVar(@SuppressWarnings("unused") TVar node)
    {
        this.index = 8;
    }

    @Override
    public void caseTCons(@SuppressWarnings("unused") TCons node)
    {
        this.index = 9;
    }

    @Override
    public void caseTAtr(@SuppressWarnings("unused") TAtr node)
    {
        this.index = 10;
    }

    @Override
    public void caseTIntTipo(@SuppressWarnings("unused") TIntTipo node)
    {
        this.index = 11;
    }

    @Override
    public void caseTBoolTipo(@SuppressWarnings("unused") TBoolTipo node)
    {
        this.index = 12;
    }

    @Override
    public void caseTRealTipo(@SuppressWarnings("unused") TRealTipo node)
    {
        this.index = 13;
    }

    @Override
    public void caseTDetProcInicial(@SuppressWarnings("unused") TDetProcInicial node)
    {
        this.index = 14;
    }

    @Override
    public void caseTProc(@SuppressWarnings("unused") TProc node)
    {
        this.index = 15;
    }

    @Override
    public void caseTParEsq(@SuppressWarnings("unused") TParEsq node)
    {
        this.index = 16;
    }

    @Override
    public void caseTParDir(@SuppressWarnings("unused") TParDir node)
    {
        this.index = 17;
    }

    @Override
    public void caseTFunc(@SuppressWarnings("unused") TFunc node)
    {
        this.index = 18;
    }

    @Override
    public void caseTSe(@SuppressWarnings("unused") TSe node)
    {
        this.index = 19;
    }

    @Override
    public void caseTSenao(@SuppressWarnings("unused") TSenao node)
    {
        this.index = 20;
    }

    @Override
    public void caseTEnquanto(@SuppressWarnings("unused") TEnquanto node)
    {
        this.index = 21;
    }

    @Override
    public void caseTIgualSimples(@SuppressWarnings("unused") TIgualSimples node)
    {
        this.index = 22;
    }

    @Override
    public void caseTPonto(@SuppressWarnings("unused") TPonto node)
    {
        this.index = 23;
    }

    @Override
    public void caseTBoolVerdadeiro(@SuppressWarnings("unused") TBoolVerdadeiro node)
    {
        this.index = 24;
    }

    @Override
    public void caseTBoolFalso(@SuppressWarnings("unused") TBoolFalso node)
    {
        this.index = 25;
    }

    @Override
    public void caseTSubt(@SuppressWarnings("unused") TSubt node)
    {
        this.index = 26;
    }

    @Override
    public void caseTEntao(@SuppressWarnings("unused") TEntao node)
    {
        this.index = 27;
    }

    @Override
    public void caseTAdc(@SuppressWarnings("unused") TAdc node)
    {
        this.index = 28;
    }

    @Override
    public void caseTMult(@SuppressWarnings("unused") TMult node)
    {
        this.index = 29;
    }

    @Override
    public void caseTDiv(@SuppressWarnings("unused") TDiv node)
    {
        this.index = 30;
    }

    @Override
    public void caseTMod(@SuppressWarnings("unused") TMod node)
    {
        this.index = 31;
    }

    @Override
    public void caseTIgualComp(@SuppressWarnings("unused") TIgualComp node)
    {
        this.index = 32;
    }

    @Override
    public void caseTMenor(@SuppressWarnings("unused") TMenor node)
    {
        this.index = 33;
    }

    @Override
    public void caseTNao(@SuppressWarnings("unused") TNao node)
    {
        this.index = 34;
    }

    @Override
    public void caseTELogico(@SuppressWarnings("unused") TELogico node)
    {
        this.index = 35;
    }

    @Override
    public void caseTOuLogico(@SuppressWarnings("unused") TOuLogico node)
    {
        this.index = 36;
    }

    @Override
    public void caseTId(@SuppressWarnings("unused") TId node)
    {
        this.index = 37;
    }

    @Override
    public void caseTCid(@SuppressWarnings("unused") TCid node)
    {
        this.index = 38;
    }

    @Override
    public void caseTNumInteiro(@SuppressWarnings("unused") TNumInteiro node)
    {
        this.index = 39;
    }

    @Override
    public void caseTNumReal(@SuppressWarnings("unused") TNumReal node)
    {
        this.index = 40;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 41;
    }
}
